name: Java CI/CD con Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construir el proyecto con Maven
        run: mvn clean install -DskipTests=true

      - name: Ejecutar tests
        run: mvn test

      - name: Guardar artefacto .jar
        run: |
          mkdir -p target-artifact
          cp target/*.jar target-artifact/

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target-artifact

      - name: Desplegar en Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jwtmanager-practices'  # nombre exacto de la app en Azure
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'target/JwtFilter-0.0.1-SNAPSHOT.jar'